# Generated by Django 4.2 on 2024-02-16 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_feedbackmodel_text_feedbackmodel_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='feedbacks',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='main_app.blogmodel'),
        ),
    ]
