# Generated by Django 4.2 on 2024-02-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_servicecategories_servicemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCategories',
            new_name='ServiceCategoryModel',
        ),
    ]
