# Generated by Django 5.0 on 2024-02-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_teammodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='image',
            field=models.ImageField(default=1, upload_to='team/'),
            preserve_default=False,
        ),
    ]
