# Generated by Django 4.2 on 2024-02-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_teammodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wd_height', models.FloatField()),
                ('wd_width', models.FloatField()),
                ('wnd_height', models.FloatField()),
                ('wnd_width', models.FloatField()),
                ('door_height', models.FloatField()),
                ('door_width', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estimate',
                'verbose_name_plural': 'Estimates',
            },
        ),
    ]
